* Netease Cloud Music
  Netease Cloud Music is a plugin that can let you listen music in Emacs.

  [[./README_cn.org][中文文档]]
** Dependences
   - mplayer

     This is the player for playing the songs.
     If you are an Arch user, you can install it by: ~sudo pacman -S mplayer~
   - request

     This is a emacs package, you can install it by: ~M-x package-install RET request RET~
** Installation
   1. Clone it.
      #+begin_src shell
        git clone https://github.com/SpringHan/netease-cloud-music.el.git ~/.emacs.d/ --depth=1
      #+end_src
   2. Require it:
      #+begin_src emacs-lisp
        ;; Add it to load path
        (add-to-list 'load-path "~/.emacs.d/netease-cloud-music.el")

        ;; Require it
        (require 'netease-cloud-music)
      #+end_src
** Keybindings
   | Key | Function                           |
   |-----+------------------------------------|
   | a   | Add the current song into playlist |
   | f   | Search song by its name            |
   | P   | Play all the songs in playlist     |
   | p   | Play the previous song in playlist |
   | n   | Play the next song in playlist     |
   | x   | Kill current playing song          |
   | >   | Seek forward                       |
   | <   | Seek backward                      |
   | ?   | Help                               |
   | h   | Help                               |
   | RET | Play the playlist song at point    |
   | SPC | Pause or continue the current song |
   | q   | Quit Netease Cloud Music           |
** Function
   - ~netease-cloud-music~

     You can use this function to open the Netease Cloud Music buffer and enter the major mode.
     If now you have opened the buffer, Emacs will switch it when you use this function.
** Variables
   - ~netease-cloud-music-repeat-mode~ (symbol)

     If you set it to ~t~, it will play the current song or song in playlist repeat after finishing play it.

   - ~netease-cloud-music-seek-second~ (string)

     This variable can change the second when you do the seek action.Default is "5".
** License
   GPL-3.0
